<table>
    <tr>
      <th>NAME</th>
      <th>CODE</th>
    </tr>
    <tr>
      <th>hghg</th>
      <th>13556</th>
    </tr>
    <tr>
      <th>hjgjg</th>
      <th>987960</th>
    </tr>
    <tr>
      <th>kjhmioio</th>
      <th>080769865</th>
    </tr>
    <tr>
      <th>BHH</th>
      <th>65376</th>
    </tr>
</table>
